name: Site preview
on:
  pull_request:
    branches: [ master ]
jobs:
  getp:
    runs-on: ubuntu-latest
    steps:
    - name: Get the preview of the website
    - id: html_preview
    - uses: actions/checkout@v2
    - uses: pavi2410/html-preview-action@v2
