name: Site preview

on:
  pull_request:
    branches: [ master ]

jobs:
  get_the_preview:

    runs-on: ubuntu-latest

    steps:
    - name: Get the preview of the website
    - id: html_preview
    - uses: actions/checkout@v2
    - uses: pavi2410/html-preview-action@v2
    -  with:
        html_file: 'index.html'
        message: ${{ format('[Click here to preview HTML page in browser]({0})', steps.html_preview.outputs.url) }}
    
