name: Site preview
on:
  pull_request:
    branches: [ master ]
jobs:
  getp:
    runs-on: ubuntu-latest
    steps:
      - name: Gte the preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'index.html'
