name: Site preview
on:
  pull_request:
    branches: [ main ]
jobs:
  website-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout the repository
        
      - name: Get the preview
        id: html_preview
        uses: pavi2410/html-preview-action@v2
        with:
          html_file: 'index.html'  
      
      - run: echo ${{steps.html_preview.outputs.url}}
        name: Get the url
